server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: C:/Users/Drissi houcem eddine/Desktop/Repo-Locale/Config-service/src/main/resources/config-repo
  application:
    name: config-service
